#include "../MAIN/def.h"

#ifndef __INICOH__
#define __INICOH__

void inicoh2(bool * TYPCO, R & dt, R epsi, int  nbco,  int ** CONT, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I,R * DCONT,R * DCONTO,  R ** NCONT, R ** VALCOH, R ** VALAMO, unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ, R * DCONTXO, R * DCONTYO, R * DCONTZO, R Pi, R Cs, bool * LIST_P, R rmu1, R rmu2, R Emu1, R Emu2, R nuu1, R nuu2, R amort);
void inicoh(bool * TYPCO, R & dt, R epsi, int  nbco,  int ** CONT, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT,R * DCONTO, R ** NCONT, R ** VALCOH, R ** VALAMO, unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ, R * DCONTXO, R * DCONTYO, R * DCONTZO, R Pi, R Cs, R Emu, R rmu, R nuu, R amort);
void inicoh_coef(R * LIST_IND, bool * TYPCO, R & dt, R epsi, int  nbco,  int ** CONT, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT,R * DCONTO, R ** NCONT, R ** VALCOH, R ** VALAMO, unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ, R * DCONTXO, R * DCONTYO, R * DCONTZO, R Pi, R Cs, R Emu, R rmu, R nuu, R amort);
void inicoh2_int_DCB(int & nint, int & nint0,int & npre, R * vs, R * LIST_IND, R H_TOT,int * LIST_B,bool * TYPCO, R & dt, R epsi, int  nbco,  int ** CONT, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT,R * DCONTO, R ** NCONT, R ** VALCOH, R ** VALAMO,  unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ, R * DCONTXO, R * DCONTYO, R * DCONTZO, R Pi, R Cs, bool * LIST_P, R rmu1, R rmu2, R Emu1, R Emu2, R nuu1, R nuu2, R amort);
void inicoh2_int_ELS(int & nint, int & nint0,int & npre, R * vs, R * LIST_IND, R H_TOT,int * LIST_B,bool * TYPCO, R & dt, R epsi, int  nbco,  int ** CONT, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT,R * DCONTO, R ** NCONT, R ** VALCOH, R ** VALAMO,  unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ, R * DCONTXO, R * DCONTYO, R * DCONTZO, R Pi, R Cs, bool * LIST_P, R rmu1, R rmu2, R Emu1, R Emu2, R nuu1, R nuu2, R amort);
void inicoh2_int_MMB(int & nint, int & nint0,int & npre, R * vs, R * LIST_IND, R H_TOT,int * LIST_B,bool * TYPCO, R & dt, R epsi, int  nbco,  int ** CONT, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT,R * DCONTO, R ** NCONT, R ** VALCOH, R ** VALAMO,  unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ, R * DCONTXO, R * DCONTYO, R * DCONTZO, R Pi, R Cs, bool * LIST_P, R rmu1, R rmu2, R Emu1, R Emu2, R nuu1, R nuu2, R amort);
void inicoh2_int_mI(int & nint, int & nint0, R * vs, R * LIST_IND, R H_TOT,int * LIST_B,bool * TYPCO, R & dt, R epsi, int  nbco,  int ** CONT, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT,R * DCONTO, R ** NCONT, R ** VALCOH, R ** VALAMO,  unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ, R * DCONTXO, R * DCONTYO, R * DCONTZO, R Pi, R Cs, bool * LIST_P, R rmu1, R rmu2, R Emu1, R Emu2, R nuu1, R nuu2, R amort);
void inicoh2_int_mII(int & nint, int & nint0, R * vs, R * LIST_IND, R H_TOT,int * LIST_B,bool * TYPCO, R & dt, R epsi, int  nbco,  int ** CONT, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT,R * DCONTO, R ** NCONT, R ** VALCOH, R ** VALAMO,  unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ, R * DCONTXO, R * DCONTYO, R * DCONTZO, R Pi, R Cs, bool * LIST_P, R rmu1, R rmu2, R Emu1, R Emu2, R nuu1, R nuu2, R amort);
void inicoh2_int_mm(int & nint, int & nint0, R * vs, R * LIST_IND, R H_TOT,int * LIST_B,bool * TYPCO, R & dt, R epsi, int  nbco,  int ** CONT, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT,R * DCONTO, R ** NCONT, R ** VALCOH, R ** VALAMO,  unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ, R * DCONTXO, R * DCONTYO, R * DCONTZO, R Pi, R Cs, bool * LIST_P, R rmu1, R rmu2, R Emu1, R Emu2, R nuu1, R nuu2, R amort);
#endif
