#include "../MAIN/def.h"

#ifndef __SELCO__
#define __SELCO__

void selco(R & dt, R epsi, int & nbco, int NB_SPH, int ** CONT, int vecsize, int vecsizex, int vecsizey, int vecsizez, int ** coul, int * nocoul, int ** numc, int * nonumc,  R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT, R * DCONTO, R ** NCONT, unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ, R Pi, R E, R nu, int & nbcop,int ** CONTP, R * DCONTP, R ** NCONTP, int NB_PAR, R ** LIST_PX, R ** LIST_PY, R ** LIST_PZ, R ** LIST_PN, int NMAXCONT, int NMAXCONTP, int NMAXZ);

void selco_paroi(R epsi, int & nbcop,int ** CONTP, R * DCONTP, R ** NCONTP, int NB_PAR, R ** LIST_PX, R ** LIST_PY, R ** LIST_PZ, R ** LIST_PN, int NB_SPH, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, int NMAXCONTP);

void selco_corci_qs(R & dt, R epsi, unsigned int & nbco,  int ** CONT, int vecsize, int vecsizex, int vecsizey, int vecsizez, R H_TOT, R V_TOT, R Z_TOT, int ** coul, int * nocoul, int ** numc, int * nonumc, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT, R ** NCONT, R ** VALCOH, R ** VALAMO, unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ, R Pi, R Cs, R Emu, R rmu, R nuu, R amort, int NMAXCONT, int NMAXZ);

void selco_corci2_qs(R & dt, R epsi, unsigned int & nbco,  int ** CONT, int vecsize, int vecsizex, int vecsizey, int vecsizez, R H_TOT, R V_TOT, R Z_TOT, int ** coul, int * nocoul, int ** numc, int * nonumc, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT, R ** NCONT, R ** VALCOH, R ** VALAMO, unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ, R Pi, R Cs, bool * LIST_P, R rmu1, R rmu2, R Emu1, R Emu2, R nuu1, R nuu2, R amort, int NMAXCONT, int NMAXZ);

void selco_corci_ori(R epsi,int NB_SPH, int & nbco,  int ** CONT, int vecsize, int vecsizex, int vecsizey, int vecsizez, int ** coul, int * nocoul, int ** numc, int * nonumc, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, unsigned int ** NOCONT, int * NBCONTCO, int NMAXCONT, int NMAXZ);

void selco_corci_ind(bool * TYPCO, R & dt, R epsi, int & nbco, int & nbcoh, int & nbcoe, int & nbci, int NB_SPH, int ** CONT, int vecsize, int vecsizex, int vecsizey, int vecsizez, R H_TOT, R V_TOT, R Z_TOT, int ** coul, int * nocoul,int ** numc, int * nonumc, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT, R * DCONTO, R ** NCONT, R ** VALCOH, R ** VALAMO, unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ, R Pi, R Cs, R E1, R nu1, R E2, R nu2, int NMAXCONT, int NMAXZ);

void selco_corci(bool * TYPCO, R & dt, R epsi, unsigned int & nbco,int & nbcoh,int & nbcoe, int NB_SPH, int ** CONT, int vecsize, int vecsizex, int vecsizey, int vecsizez, R H_TOT, R V_TOT, R Z_TOT, int ** coul, int * nocoul,int ** numc, int * nonumc, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT,R * DCONTO, R ** NCONT, R ** VALCOH, R ** VALAMO, unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ, R Pi, R Cs, R E, R nu, int NMAXCONT, int NMAXZ);

void selco_corci2(bool * TYPCO, R & dt, R epsi, unsigned int & nbco,int & nbcoh,int & nbcoe, int NB_SPH, int ** CONT, int vecsize, int vecsizex, int vecsizey, int vecsizez, R H_TOT, R V_TOT, R Z_TOT, int ** coul, int * nocoul,int ** numc, int * nonumc, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT,R * DCONTO, R ** NCONT, R ** VALCOH, R ** VALAMO, unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ, R Pi, R Cs, R E1, R nu1, R E2, R nu2, bool * LIST_P, int NMAXCONT, int NMAXZ);

void selco_corci0(bool * TYPCO, R & dt, int & nbco, int NB_SPH, int ** CONT, R * LIST_R, R * LIST_M, R * LIST_I, R * DCONT, R ** NCONT, R ** VALCOH, R ** VALAMO, unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ, R Cs, int NMAXCONT, int NMAXZ);

void selco_corci2_mI(int & nint,int & nsoft,R Kcon, R * vs,R * LIST_VX, R * LIST_VY, R * LIST_VZ,bool * TYPCO, R & dt, R epsi, int & nbco,int & nbcoh,int & nbcoe, int NB_SPH, int ** CONT, int vecsize, int ** coul, int * nocoul, int ** numc, int * nonumc, R * LIST_IND, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT,R * DCONTO, R ** NCONT, R ** VALCOH, R ** VALAMO, unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ,R * DCONTXO, R * DCONTYO, R * DCONTZO, R Pi, R Cs, R E1, R nu1, R E2, R nu2, R Emu1, R rmu1, R Emu2, R rmu2, R amort, bool * LIST_P, int * LIST_B, int ite,  R GI, R GII, R snmax, R ssmax);

void selco_corci2_mIexp(int & nint,int & nsoft,R Kcon, R * vs,R * LIST_VX, R * LIST_VY, R * LIST_VZ,bool * TYPCO, R & dt, R epsi, int & nbco,int & nbcoh,int & nbcoe, int NB_SPH, int ** CONT, int vecsize, int ** coul, int * nocoul, int ** numc, int * nonumc, R * LIST_IND, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT,R * DCONTO, R ** NCONT, R ** VALCOH, R ** VALAMO, unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ,R * DCONTXO, R * DCONTYO, R * DCONTZO, R Pi, R Cs, R E1, R nu1, R E2, R nu2, R Emu1, R rmu1, R Emu2, R rmu2, R amort, bool * LIST_P, int * LIST_B, int ite,  R GI, R GII, R snmax, R ssmax);

void selco_corci2_mII(int & nint,int & nsoft,R Kcon, R * vs,R * LIST_VX, R * LIST_VY, R * LIST_VZ,bool * TYPCO, R & dt, R epsi, int & nbco,int & nbcoh,int & nbcoe, int NB_SPH, int ** CONT, int vecsize, int ** coul, int * nocoul, int ** numc, int * nonumc, R * LIST_IND, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT,R * DCONTO, R ** NCONT, R ** VALCOH, R ** VALAMO, unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ,R * DCONTXO, R * DCONTYO, R * DCONTZO, R Pi, R Cs, R E1, R nu1, R E2, R nu2, R Emu1, R rmu1, R Emu2, R rmu2, R amort, bool * LIST_P, int * LIST_B, int ite,  R GI, R GII, R snmax, R ssmax);

void selco_corci2_mm(int & nint,int & nsoft,R Kcon, R * vs,R * LIST_VX, R * LIST_VY, R * LIST_VZ,bool * TYPCO, R & dt, R epsi, int & nbco,int & nbcoh,int & nbcoe, int NB_SPH, int ** CONT, int vecsize, int ** coul, int * nocoul, int ** numc, int * nonumc, R * LIST_IND, R * LIST_R, R * LIST_X, R * LIST_Y, R * LIST_Z, R * LIST_M, R * LIST_I, R * DCONT,R * DCONTO, R ** NCONT, R ** VALCOH, R ** VALAMO, unsigned int ** NOCONT, int * NBCONTCO, R * DCONTX, R * DCONTY, R * DCONTZ,R * DCONTXO, R * DCONTYO, R * DCONTZO, R Pi, R Cs, R E1, R nu1, R E2, R nu2, R Emu1, R rmu1, R Emu2, R rmu2, R amort, bool * LIST_P, int * LIST_B, int ite,  R GI, R GII, R snmax, R ssmax);
#endif
